import { useNavigate } from "react-router-dom"
import { Logo } from "@/components/Logo"
import { ArrowLeft } from "lucide-react"
import { DynamicMeta } from "@/components/DynamicMeta"

export function PrivacyPolicy() {
  const navigate = useNavigate()

  return (
    <>
      <DynamicMeta
        path="/privacy"
        title="Privacy Policy - Torale"
        description="Privacy policy for Torale. Learn how we protect your data and monitoring queries."
      />
      <div className="min-h-screen bg-[#fafafa]">
      {/* Header */}
      <header className="sticky top-0 z-50 w-full bg-[#fafafa]/90 backdrop-blur-md border-b border-zinc-200">
        <div className="container mx-auto px-6 h-16 flex items-center justify-between">
          <button onClick={() => navigate('/')} className="cursor-pointer">
            <Logo />
          </button>
          <button
            onClick={() => navigate('/')}
            className="flex items-center gap-2 text-sm font-bold text-zinc-900 hover:text-ink-1 transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Home
          </button>
        </div>
      </header>

      {/* Content */}
      <main className="container mx-auto max-w-4xl px-6 py-16">
        <div className="bg-white border border-zinc-200 shadow-ww-md p-12">
          <h1 className="text-4xl font-bold text-zinc-900 mb-2">Privacy Policy</h1>
          <p className="text-sm text-zinc-500 font-mono mb-12">Effective Date: December 2, 2025</p>

          <div className="prose prose-zinc max-w-none space-y-8">
            {/* Introduction */}
            <section>
              <h2 className="text-2xl font-bold text-zinc-900 mb-4">1. Introduction</h2>
              <p className="text-zinc-600 leading-relaxed">
                Torale Labs Inc. ("we," "us," "our") operates the Torale web monitoring platform ("Service").
                This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you
                use our Service.
              </p>
            </section>

            {/* Information We Collect */}
            <section>
              <h2 className="text-2xl font-bold text-zinc-900 mb-4">2. Information We Collect</h2>

              <h3 className="text-xl font-bold text-zinc-900 mb-3 mt-6">2.1 Account Information</h3>
              <p className="text-zinc-600 leading-relaxed mb-4">When you create an account, we collect:</p>
              <ul className="list-disc pl-6 text-zinc-600 space-y-2">
                <li><strong>Email address:</strong> Used for authentication, account recovery, and service communications</li>
                <li><strong>Authentication credentials:</strong> Password hash (if using email/password) or OAuth tokens (if using Google/GitHub login) managed by our authentication provider, Clerk</li>
                <li><strong>User ID:</strong> Unique identifier generated by our system and synced with Clerk</li>
                <li><strong>Account metadata:</strong> Creation date, last login, account status (active/inactive)</li>
              </ul>

              <h3 className="text-xl font-bold text-zinc-900 mb-3 mt-6">2.2 Task and Monitoring Data</h3>
              <p className="text-zinc-600 leading-relaxed mb-4">When you create monitoring tasks, we collect:</p>
              <ul className="list-disc pl-6 text-zinc-600 space-y-2">
                <li><strong>Search queries:</strong> The questions or topics you want to monitor (e.g., "When is the iPhone 17 release?")</li>
                <li><strong>Condition descriptions:</strong> Criteria you define for triggering notifications (e.g., "A specific date has been announced")</li>
                <li><strong>Schedules:</strong> Cron expressions defining execution frequency</li>
                <li><strong>Notification preferences:</strong> How you want to be notified (once, always)</li>
              </ul>

              <h3 className="text-xl font-bold text-zinc-900 mb-3 mt-6">2.3 Execution and Results Data</h3>
              <p className="text-zinc-600 leading-relaxed mb-4">When tasks execute, we store:</p>
              <ul className="list-disc pl-6 text-zinc-600 space-y-2">
                <li><strong>Execution metadata:</strong> Start time, completion time, status (success/failed), error messages</li>
                <li><strong>LLM-generated responses:</strong> Answers synthesized by AI models from search results</li>
                <li><strong>Condition evaluation results:</strong> Boolean determination of whether your condition was met</li>
                <li><strong>Grounding sources:</strong> URLs and metadata of web sources used to generate answers</li>
                <li><strong>Agent memory:</strong> Cross-run context used for change detection</li>
                <li><strong>Change summaries:</strong> Human-readable descriptions of what changed since the last execution</li>
              </ul>

              <h3 className="text-xl font-bold text-zinc-900 mb-3 mt-6">2.4 API Keys</h3>
              <p className="text-zinc-600 leading-relaxed mb-4">When you generate API keys for programmatic access, we collect:</p>
              <ul className="list-disc pl-6 text-zinc-600 space-y-2">
                <li><strong>Key hash:</strong> SHA256 hash of the API key (never stored in plain text)</li>
                <li><strong>Key prefix:</strong> Display-only prefix for identification (e.g., "sk_...abc123")</li>
                <li><strong>Key name:</strong> User-defined label (e.g., "Production API Key")</li>
                <li><strong>Usage metadata:</strong> Creation date, last used timestamp</li>
              </ul>

              <h3 className="text-xl font-bold text-zinc-900 mb-3 mt-6">2.5 Usage and Analytics Data</h3>
              <p className="text-zinc-600 leading-relaxed mb-4">We automatically collect:</p>
              <ul className="list-disc pl-6 text-zinc-600 space-y-2">
                <li><strong>System logs:</strong> API requests, error traces, performance metrics</li>
                <li><strong>Scheduling data:</strong> Job execution IDs, schedule metadata, retry attempts</li>
                <li><strong>Aggregate statistics:</strong> Platform-wide metrics like total tasks, execution counts, popular queries</li>
                <li><strong>IP addresses:</strong> For security, fraud prevention, and rate limiting (not linked to user profiles)</li>
              </ul>
            </section>

            {/* How We Use Information */}
            <section>
              <h2 className="text-2xl font-bold text-zinc-900 mb-4">3. How We Use Your Information</h2>
              <p className="text-zinc-600 leading-relaxed mb-4">We use collected information to:</p>
              <ul className="list-disc pl-6 text-zinc-600 space-y-2">
                <li><strong>Provide the Service:</strong> Execute monitoring tasks, evaluate conditions, send notifications</li>
                <li><strong>Improve Service quality:</strong> Analyze aggregate usage patterns, identify bugs, optimize performance</li>
                <li><strong>Customer support:</strong> Troubleshoot issues, respond to inquiries, assist with account management</li>
                <li><strong>Security and fraud prevention:</strong> Detect abuse, enforce rate limits, prevent unauthorized access</li>
                <li><strong>Legal compliance:</strong> Respond to lawful requests, enforce Terms of Service</li>
                <li><strong>Product development:</strong> Understand feature usage, prioritize roadmap items (using aggregated, non-identifiable data)</li>
              </ul>
            </section>

            {/* Data Sharing */}
            <section>
              <h2 className="text-2xl font-bold text-zinc-900 mb-4">4. How We Share Your Information</h2>

              <h3 className="text-xl font-bold text-zinc-900 mb-3 mt-6">4.1 Third-Party Service Providers</h3>
              <p className="text-zinc-600 leading-relaxed mb-4">We share data with trusted third-party providers:</p>
              <ul className="list-disc pl-6 text-zinc-600 space-y-2 mb-4">
                <li><strong>Clerk:</strong> Authentication, user management, session handling</li>
                <li><strong>Google Cloud Platform:</strong> Hosting, compute infrastructure, managed databases</li>
                <li><strong>APScheduler:</strong> Cron-based task scheduling and execution</li>
                <li><strong>AI Providers (Anthropic Claude, Perplexity):</strong> LLM inference for condition evaluation and answer generation</li>
              </ul>
              <p className="text-zinc-600 leading-relaxed mb-4">
                <strong>Important:</strong> Your search queries and monitored content are transmitted to AI providers for processing.
                These providers may use inputs to improve their models unless you opt out through their respective settings.
              </p>

              <h3 className="text-xl font-bold text-zinc-900 mb-3 mt-6">4.2 Legal Requirements</h3>
              <p className="text-zinc-600 leading-relaxed mb-4">
                We may disclose your information if required by law, subpoena, or other legal process, or if we believe
                disclosure is necessary to:
              </p>
              <ul className="list-disc pl-6 text-zinc-600 space-y-2">
                <li>Comply with legal obligations</li>
                <li>Protect our rights, property, or safety</li>
                <li>Prevent fraud or abuse</li>
                <li>Enforce our Terms of Service</li>
              </ul>

              <h3 className="text-xl font-bold text-zinc-900 mb-3 mt-6">4.3 Business Transfers</h3>
              <p className="text-zinc-600 leading-relaxed">
                If Torale Labs Inc. is involved in a merger, acquisition, or sale of assets, your information may be
                transferred as part of that transaction. We will notify you via email of any such change in ownership.
              </p>
            </section>

            {/* Administrative Access */}
            <section>
              <h2 className="text-2xl font-bold text-zinc-900 mb-4">5. Administrative Access to Data</h2>

              <div className="bg-blue-50 border-l-4 border-blue-500 p-6 mb-6">
                <h3 className="text-lg font-bold text-blue-900 mb-2">🔍 Transparency Notice</h3>
                <p className="text-blue-800 text-sm leading-relaxed">
                  Torale administrators have access to user data through an internal administrative console for operational
                  and support purposes. We believe in transparency about how your data is accessed.
                </p>
              </div>

              <p className="text-zinc-600 leading-relaxed mb-4">
                <strong className="text-zinc-900">Who Has Access:</strong> Only authorized Torale employees and contractors
                with a legitimate business need can access the Admin Console.
              </p>

              <p className="text-zinc-600 leading-relaxed mb-4">
                <strong className="text-zinc-900">What They Can See:</strong>
              </p>
              <ul className="list-disc pl-6 text-zinc-600 space-y-2 mb-4">
                <li>User account information (email, creation date, activity stats)</li>
                <li>Task configurations (search queries, conditions, schedules)</li>
                <li>Execution history (results, LLM responses, grounding sources)</li>
                <li>Platform statistics (popular queries, error rates, system health)</li>
                <li>Scheduling metadata (execution status, cron schedules)</li>
              </ul>

              <p className="text-zinc-600 leading-relaxed mb-4">
                <strong className="text-zinc-900">Why Access Is Needed:</strong>
              </p>
              <ul className="list-disc pl-6 text-zinc-600 space-y-2 mb-4">
                <li>Debugging technical issues reported by users</li>
                <li>Investigating service outages or performance degradation</li>
                <li>Detecting and preventing abuse, spam, or Terms violations</li>
                <li>Generating aggregate analytics to improve the Service</li>
                <li>Responding to legal requests or security incidents</li>
              </ul>

              <p className="text-zinc-600 leading-relaxed">
                <strong className="text-zinc-900">Access Controls:</strong> Admin Console access is logged, audited, and
                restricted to employees bound by confidentiality agreements. We do not sell, share, or use your data for
                purposes unrelated to providing and improving the Service.
              </p>
            </section>

            {/* Data Security */}
            <section>
              <h2 className="text-2xl font-bold text-zinc-900 mb-4">6. Data Security</h2>
              <p className="text-zinc-600 leading-relaxed mb-4">We implement industry-standard security measures:</p>
              <ul className="list-disc pl-6 text-zinc-600 space-y-2">
                <li><strong>Encryption:</strong> TLS 1.3 for data in transit, AES-256 for data at rest</li>
                <li><strong>Authentication:</strong> Clerk-managed OAuth and email/password with bcrypt hashing</li>
                <li><strong>API key security:</strong> SHA256 hashing, no plain-text storage</li>
                <li><strong>Database security:</strong> Cloud SQL with private IP, automated backups, point-in-time recovery</li>
                <li><strong>Infrastructure:</strong> GKE Autopilot with network policies, Workload Identity, least-privilege IAM</li>
                <li><strong>Access logging:</strong> All administrative actions are logged and auditable</li>
              </ul>
              <p className="text-zinc-600 leading-relaxed mt-4">
                However, no method of transmission or storage is 100% secure. We cannot guarantee absolute security.
              </p>
            </section>

            {/* Data Retention */}
            <section>
              <h2 className="text-2xl font-bold text-zinc-900 mb-4">7. Data Retention</h2>
              <p className="text-zinc-600 leading-relaxed mb-4">We retain your information:</p>
              <ul className="list-disc pl-6 text-zinc-600 space-y-2">
                <li><strong>Active accounts:</strong> For the duration of your account</li>
                <li><strong>Deleted accounts:</strong> 90 days after account deletion (for recovery and legal purposes)</li>
                <li><strong>Execution history:</strong> Indefinitely while your account is active; deleted 90 days after account deletion</li>
                <li><strong>System logs:</strong> 30 days for debugging; 1 year for security logs</li>
                <li><strong>Aggregated analytics:</strong> Retained indefinitely (anonymized, non-identifiable)</li>
              </ul>
            </section>

            {/* Your Rights */}
            <section>
              <h2 className="text-2xl font-bold text-zinc-900 mb-4">8. Your Privacy Rights</h2>
              <p className="text-zinc-600 leading-relaxed mb-4">Depending on your jurisdiction, you may have the right to:</p>
              <ul className="list-disc pl-6 text-zinc-600 space-y-2">
                <li><strong>Access:</strong> Request a copy of your personal data</li>
                <li><strong>Correction:</strong> Update or correct inaccurate information</li>
                <li><strong>Deletion:</strong> Request deletion of your account and associated data</li>
                <li><strong>Data portability:</strong> Export your task configurations and execution history in JSON format</li>
                <li><strong>Opt-out:</strong> Unsubscribe from marketing emails (we currently send none)</li>
                <li><strong>Restrict processing:</strong> Request limitations on how we use your data</li>
              </ul>
              <p className="text-zinc-600 leading-relaxed mt-4">
                To exercise these rights, contact <a href="mailto:privacy@torale.ai" className="text-ink-1 hover:underline">privacy@torale.ai</a>.
                We will respond within 30 days.
              </p>
            </section>

            {/* International Transfers */}
            <section>
              <h2 className="text-2xl font-bold text-zinc-900 mb-4">9. International Data Transfers</h2>
              <p className="text-zinc-600 leading-relaxed">
                The Service is hosted in the United States (Google Cloud us-central1 region). If you access the Service
                from outside the US, your data will be transferred to and processed in the United States. By using the
                Service, you consent to this transfer.
              </p>
            </section>

            {/* Children's Privacy */}
            <section>
              <h2 className="text-2xl font-bold text-zinc-900 mb-4">10. Children's Privacy</h2>
              <p className="text-zinc-600 leading-relaxed">
                The Service is not intended for users under 18 years of age. We do not knowingly collect personal information
                from children. If you believe we have collected data from a child, contact <a href="mailto:privacy@torale.ai" className="text-ink-1 hover:underline">privacy@torale.ai</a>.
              </p>
            </section>

            {/* Cookies and Tracking */}
            <section>
              <h2 className="text-2xl font-bold text-zinc-900 mb-4">11. Cookies and Tracking</h2>
              <p className="text-zinc-600 leading-relaxed mb-4">
                We use essential cookies for authentication and session management via Clerk. We do not use third-party
                analytics, advertising cookies, or tracking pixels.
              </p>
              <p className="text-zinc-600 leading-relaxed">
                You can disable cookies in your browser settings, but this may affect Service functionality.
              </p>
            </section>

            {/* Changes to Policy */}
            <section>
              <h2 className="text-2xl font-bold text-zinc-900 mb-4">12. Changes to This Privacy Policy</h2>
              <p className="text-zinc-600 leading-relaxed">
                We may update this Privacy Policy from time to time. Material changes will be communicated via email or
                in-app notification. Continued use of the Service after changes constitutes acceptance of the updated policy.
              </p>
            </section>

            {/* Contact */}
            <section>
              <h2 className="text-2xl font-bold text-zinc-900 mb-4">13. Contact Us</h2>
              <p className="text-zinc-600 leading-relaxed mb-4">
                For questions, concerns, or requests regarding this Privacy Policy or your personal data:
              </p>
              <div className="p-4 bg-zinc-50 border border-zinc-200 rounded font-mono text-sm">
                <p className="text-zinc-900">Torale Labs Inc.</p>
                <p className="text-zinc-600">Privacy Officer</p>
                <p className="text-zinc-600">Email: <a href="mailto:privacy@torale.ai" className="text-ink-1 hover:underline">privacy@torale.ai</a></p>
              </div>
            </section>
          </div>
        </div>
      </main>
    </div>
    </>
  )
}
